### ISSUE TITLE
Converted maps are in the ground.

### ISSUE THREAD

**Issue by renefreund** [BigBang1112/nations-converter#6]
Hi,

very nice tool. But somehow version 1.0.0 convertes all maps with a negative Z-index (height), so ground-layered items are 1-3 heights under the grass if i open them in tm2020.

tried about 40 maps from tmnf and tm2 stadium.

i added a (source-files)
* tmnf map [Mars Attack.Map.zip](https://github.com/BigBang1112/nations-converter/files/5681646/Mars.Attack.Map.zip)
* tm2 map [»»»Nazzcar01-Driver's Fun«««.Map.zip](https://github.com/BigBang1112/nations-converter/files/5681639/Nazzcar01-Driver.s.Fun.Map.zip)

greetings.

**Comment by renefreund** [comment]
Added a tm2020-editor screenshot from a converted map as example.

![marsattacks_converted_example_for_wrong base-height](https://user-images.githubusercontent.com/4696183/101956058-3bbeee80-3bff-11eb-95ff-cf4924fd048d.png)

btw. no openplanet present in my client.

**Comment by BigBang1112** [comment]
This sounds like a map built in either an unusual version of the newest TMNF. Weird

**Comment by renefreund** [comment]
to be clear. all my mapfiles BEFORE

* 2013 (tmnf)
* 2105 (tm2, maybe from ghost of tmnf to tm2 converted)

if its edgecases.. pls close. but i think mars attack map should be okay to debug.

**Comment by zai-tm** [comment]
Try re-saving the maps (with a different name, of course), then converting it

**Comment by BigBang1112** [comment]
Converter should recognize every Stadium map correctly, so I don't count resaving as the definite solution. I will look at this issue once I get through the priorities.

**Comment by BigBang1112** [comment]
Hello, after a long time, I figured out the issue.
Maps can get sunk to the ground because they were made at the game release date. Back then, it likely used to happen that the chunk 0x03043052 (decoration height chunk) didn't appear in maps most of the time. This chunk gives a property [DecoBaseHeightOffset](https://github.com/BigBang1112/gbx-net/blob/6fc66492f14e198becf31085d9d3c7cce8090d9b/GBX.NET/Engines/Game/CGameCtnChallenge.cs#L1047) likely determining that the blocks are shifted up by 8 units by default. This wasn't included back then, and the block Y started at 0.

This bug has been fixed in two commits: 32a03534aff2dd5b53d0c53b4d7117a5bec1a219 85bd24cfb50fd8281c0c26b1dc13b7599e82eb1e
